### ISSUE TITLE
add RSDL syntax highlighting for Github markdown code blocks

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#285] opened 2021-09-13 18:15 UTC
https://docs.github.com/en/enterprise-server@3.1/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by ralfhandl** [comment] 2021-09-14 06:58
Seems to be a duplicate of #223.

Also see steps for adding to linguist here: https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language, I assume we are a bit short of "200 unique `:user/:repo` repositories":

Note:
> We try only to add languages once they have some usage on GitHub.
In most cases we prefer that each new file extension be in use in *at least 200 unique `:user/:repo` repositories* before supporting them in Linguist.

**Comment by chrisspre** [comment] 2021-09-14 18:09
I didn't drill into the details. Was actually expecting there is a per-repo configuration/overwrite for the languages file.

**Comment by ralfhandl** [comment] 2021-09-15 06:47
Linguist allows overrides per repo or file, see https://github.com/github/linguist/blob/master/docs/overrides.md, I used this to get highlighting for the OData ABNF in `*.txt` files: https://github.com/oasis-tcs/odata-abnf/blob/main/.gitattributes.

I assume this mechanism is limited to officially listed languages.

**Closed** 2021-09-23 15:08 UTC
Labels: duplicate
